"""Seed data focused on Bengaluru service providers.
This is dummy data inspired by typical local listings so we can showcase the India-first experience
without copying any proprietary marketplace content.
"""
from __future__ import annotations

from datetime import datetime, timedelta
import bcrypt
from typing import Dict, List

# Helper functions -----------------------------------------------------------
def _now(days_offset: int = 0) -> datetime:
    return datetime.utcnow() - timedelta(days=days_offset)


def _hash_password(password: str) -> str:
    return bcrypt.hashpw(password.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


# Seed USERS -----------------------------------------------------------------
SEED_USERS: List[Dict] = [
    # Admin test accounts (for testing and moderation)
    {
        "id": "user1",
        "email": "techreviewer@example.com",
        "full_name": "Tech Reviewer",
        "username": "TechReviewer2024",
        "password": _hash_password("password123"),
        "is_active": True,
        "created_at": _now(90),
        "review_count": 3,
        "reputation_score": 95,
    },
    {
        "id": "user2",
        "email": "pmmanager@example.com",
        "full_name": "Project Manager",
        "username": "ProjectManager_Pro",
        "password": _hash_password("password123"),
        "is_active": True,
        "created_at": _now(100),
        "review_count": 2,
        "reputation_score": 88,
    },
    # Bengaluru local users
    {
        "id": "blr_user_1",
        "email": "aditi.rao@example.com",
        "full_name": "Aditi Rao",
        "username": "aditi_hsr",
        "password": _hash_password("nammaBLR2024"),
        "is_active": True,
        "created_at": _now(30),
        "review_count": 6,
        "reputation_score": 90,
    },
    {
        "id": "blr_user_2",
        "email": "rahul.menon@example.com",
        "full_name": "Rahul Menon",
        "username": "rahul_koramangala",
        "password": _hash_password("fixitnow"),
        "is_active": True,
        "created_at": _now(45),
        "review_count": 5,
        "reputation_score": 82,
    },
    {
        "id": "blr_user_3",
        "email": "sahana.gs@example.com",
        "full_name": "Sahana G S",
        "username": "sahana_whitefield",
        "password": _hash_password("bengaluru123"),
        "is_active": True,
        "created_at": _now(12),
        "review_count": 4,
        "reputation_score": 88,
    },
    {
        "id": "blr_user_4",
        "email": "mohit.agarwal@example.com",
        "full_name": "Mohit Agarwal",
        "username": "mohit_ulsoor",
        "password": _hash_password("trustedwork"),
        "is_active": True,
        "created_at": _now(5),
        "review_count": 3,
        "reputation_score": 79,
    },
    {
        "id": "blr_user_5",
        "email": "revathi.nair@example.com",
        "full_name": "Revathi Nair",
        "username": "revathi_indiranagar",
        "password": _hash_password("localheroes"),
        "is_active": True,
        "created_at": _now(60),
        "review_count": 7,
        "reputation_score": 95,
    },
]

# Seed PERSONS ----------------------------------------------------------------
BANGALORE_VENDORS: List[Dict] = [
    {
        "id": "blr_vendor_001",
        "name": "Sri Lakshmi Hardware & Paints",
        "company": "Sri Lakshmi Hardware & Paints",
        "job_title": "Hardware & Paint Store",
        "category": "Hardware Store",
        "industry": "Local Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Indiranagar 100 Feet Road",
        "phone": "+91 98860 11223",
        "whatsapp_number": "+91 9886011223",
        "google_maps_url": "https://maps.app.goo.gl/example1",
        "bio": "Trusted neighborhood hardware shop with on-call delivery for plumbers and interior crews.",
        "skills": [
            "Paint mixing",
            "Plumbing spares",
            "Electrical fitments",
            "Power tools rental",
        ],
        "services_offered": ["Same-day delivery", "Contractor credit", "Bulk discounts"],
        "languages": ["Kannada", "English", "Hindi"],
        "payment_modes": ["UPI", "Cash", "Cards"],
        "established_year": 1998,
    },
    {
        "id": "blr_vendor_002",
        "name": "Indus Woodcraft",
        "company": "Indus Woodcraft",
        "job_title": "Custom Carpenter",
        "category": "Carpenter",
        "industry": "Home Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Koramangala 4th Block",
        "phone": "+91 98453 77661",
        "whatsapp_number": "+91 9845377661",
        "google_maps_url": "https://maps.app.goo.gl/example2",
        "bio": "Made-to-order wardrobes, modular kitchens, and onsite repairs for apartments across Koramangala & HSR.",
        "skills": ["Modular carpentry", "Onsite repairs", "Polishing"],
        "services_offered": ["Designer consultation", "Material sourcing", "Annual maintenance"],
        "languages": ["Kannada", "English", "Tamil"],
        "payment_modes": ["UPI", "Cash", "Net Banking"],
        "established_year": 2010,
    },
    {
        "id": "blr_vendor_003",
        "name": "Namma Plumbers Collective",
        "company": "Namma Plumbers Collective",
        "job_title": "Emergency Plumbers",
        "category": "Plumber",
        "industry": "Home Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "HSR Layout Sector 2",
        "phone": "+91 99802 44119",
        "whatsapp_number": "+91 9980244119",
        "google_maps_url": "https://maps.app.goo.gl/example3",
        "bio": "Collective of licensed plumbers covering Bellandur, HSR and Sarjapur Road with 45-min response time.",
        "skills": ["Leak fixing", "Bathroom remodel", "Water tank cleaning"],
        "services_offered": ["Emergency visits", "AMC for societies", "Corporate billing"],
        "languages": ["Kannada", "English"],
        "payment_modes": ["UPI", "Cash"],
        "established_year": 2015,
    },
    {
        "id": "blr_vendor_004",
        "name": "Brightline Electricals",
        "company": "Brightline Electricals",
        "job_title": "Certified Electricians",
        "category": "Electrician",
        "industry": "Home Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Whitefield - ITPL Main Road",
        "phone": "+91 63620 88441",
        "whatsapp_number": "+91 6362088441",
        "google_maps_url": "https://maps.app.goo.gl/example4",
        "bio": "Handles office fit-outs, safety audits, and 24/7 emergency visits for gated communities in Whitefield.",
        "skills": ["Panel installation", "DG maintenance", "Smart home wiring"],
        "services_offered": ["Emergency support", "Safety audits", "Annual contracts"],
        "languages": ["Kannada", "English", "Hindi"],
        "payment_modes": ["UPI", "Cash", "NEFT"],
        "established_year": 2012,
    },
    {
        "id": "blr_vendor_005",
        "name": "HSR Fresh Greens",
        "company": "HSR Fresh Greens",
        "job_title": "Organic Vegetable Vendor",
        "category": "Fresh Produce",
        "industry": "Food Supply",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "HSR Layout BDA Complex",
        "phone": "+91 81230 22118",
        "whatsapp_number": "+91 8123022118",
        "google_maps_url": "https://maps.app.goo.gl/example5",
        "bio": "Farm-direct veggies delivered daily to HSR apartments with easy subscription management over WhatsApp.",
        "skills": ["Hydroponic greens", "Subscription logistics"],
        "services_offered": ["Daily delivery", "Bulk orders", "Festival hampers"],
        "languages": ["Kannada", "English", "Malayalam"],
        "payment_modes": ["UPI", "Cash"],
        "established_year": 2019,
    },
    {
        "id": "blr_vendor_006",
        "name": "Ulsoor Sofa Repair Studio",
        "company": "Ulsoor Sofa Repair Studio",
        "job_title": "Furniture Repair",
        "category": "Upholstery",
        "industry": "Home Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Ulsoor Lake Road",
        "phone": "+91 95380 77654",
        "whatsapp_number": "+91 9538077654",
        "google_maps_url": "https://maps.app.goo.gl/example6",
        "bio": "Same-day onsite sofa repair, leather rework, and cushion upgrades for central Bengaluru homes.",
        "skills": ["Leather work", "Customized cushions", "Recliner repair"],
        "services_offered": ["Doorstep service", "Pickup & drop", "Warranty support"],
        "languages": ["Kannada", "English", "Hindi"],
        "payment_modes": ["UPI", "Cash", "Cards"],
        "established_year": 2005,
    },
    {
        "id": "blr_vendor_007",
        "name": "Sarjapur Cycle Works",
        "company": "Sarjapur Cycle Works",
        "job_title": "Cycle & E-bike Service",
        "category": "Repair Shop",
        "industry": "Mobility",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Sarjapur Road - Kaikondrahalli",
        "phone": "+91 70199 66322",
        "whatsapp_number": "+91 7019966322",
        "google_maps_url": "https://maps.app.goo.gl/example7",
        "bio": "Mobile service van for cycles & e-bikes, popular with weekend riders and apartment communities.",
        "skills": ["E-bike firmware", "Wheel truing", "Pickup service"],
        "services_offered": ["Annual maintenance", "Community camps", "Spare sales"],
        "languages": ["Kannada", "English"],
        "payment_modes": ["UPI", "Cash"],
        "established_year": 2017,
    },
    {
        "id": "blr_vendor_008",
        "name": "JP Nagar Tiffin Collective",
        "company": "JP Nagar Tiffin Collective",
        "job_title": "Home-style Catering",
        "category": "Tiffin Service",
        "industry": "Food Supply",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "JP Nagar Phase 3",
        "phone": "+91 80881 22554",
        "whatsapp_number": "+91 8088122554",
        "google_maps_url": "https://maps.app.goo.gl/example8",
        "bio": "Collective of five home chefs delivering vegetarian tiffins with calorie tracking for young professionals.",
        "skills": ["Diet meals", "Festival catering"],
        "services_offered": ["Weekly subscription", "Corporate lunch", "NRI family packs"],
        "languages": ["Kannada", "Hindi", "English"],
        "payment_modes": ["UPI", "Cash"],
        "established_year": 2020,
    },
    {
        "id": "blr_vendor_009",
        "name": "Malleshwaram Instrument Repairs",
        "company": "Malleshwaram Instrument Repairs",
        "job_title": "Music Instrument Repair",
        "category": "Repair Shop",
        "industry": "Creative Services",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Malleshwaram 8th Cross",
        "phone": "+91 99452 11290",
        "whatsapp_number": "+91 9945211290",
        "google_maps_url": "https://maps.app.goo.gl/example9",
        "bio": "Specialists in veena, violin, and acoustic guitar maintenance serving classical musicians across Bengaluru.",
        "skills": ["String replacement", "Acoustic calibration", "Vintage restoration"],
        "services_offered": ["Studio pickup", "Festival readiness", "School partnerships"],
        "languages": ["Kannada", "English", "Tamil"],
        "payment_modes": ["UPI", "Cash", "Cards"],
        "established_year": 1992,
    },
    {
        "id": "blr_vendor_010",
        "name": "Hebbal Pet Patrol",
        "company": "Hebbal Pet Patrol",
        "job_title": "Mobile Pet Grooming",
        "category": "Pet Services",
        "industry": "Pet Care",
        "city": "Bengaluru",
        "state": "Karnataka",
        "country": "India",
        "area": "Hebbal & RT Nagar",
        "phone": "+91 96111 44802",
        "whatsapp_number": "+91 9611144802",
        "google_maps_url": "https://maps.app.goo.gl/example10",
        "bio": "On-van pet grooming, vet tie-ups, and subscription baths for northern Bengaluru pet parents.",
        "skills": ["Pet grooming", "Vet coordination", "Mobile spa"],
        "services_offered": ["Doorstep grooming", "Emergency clean-ups", "Adoption support"],
        "languages": ["Kannada", "English"],
        "payment_modes": ["UPI", "Cash", "Cards"],
        "established_year": 2018,
    },
]

# Seed REVIEWS ---------------------------------------------------------------
SEED_REVIEWS: List[Dict] = [
    {
        "id": "blr_review_001",
        "person_id": "blr_vendor_001",
        "reviewer_id": "blr_user_1",
        "reviewer_username": "aditi_hsr",
        "rating": 5,
        "title": "Trusted for last-minute fixes",
        "comment": "They always stock odd-sized screws and even dispatch a delivery boy within 30 minutes to HSR.",
        "relationship": "customer",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(3),
        "updated_at": _now(3),
        "is_verified": True,
        "helpful_count": 4,
        "reported_count": 0,
    },
    {
        "id": "blr_review_002",
        "person_id": "blr_vendor_001",
        "reviewer_id": "blr_user_2",
        "reviewer_username": "rahul_koramangala",
        "rating": 4,
        "title": "Bulk discounts are neat",
        "comment": "Good for society projects. Wish they accepted online invoicing but UPI works fine.",
        "relationship": "society secretary",
        "work_quality": 4,
        "communication": 4,
        "reliability": 5,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(10),
        "updated_at": _now(10),
        "is_verified": True,
        "helpful_count": 2,
        "reported_count": 0,
    },
    {
        "id": "blr_review_003",
        "person_id": "blr_vendor_002",
        "reviewer_id": "blr_user_3",
        "reviewer_username": "sahana_whitefield",
        "rating": 5,
        "title": "Wardrobe done in 6 days",
        "comment": "Clear pricing and he shared 3D drawings on WhatsApp. Workers cleaned up after work which is rare!",
        "relationship": "customer",
        "work_quality": 5,
        "communication": 4,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(7),
        "updated_at": _now(7),
        "is_verified": True,
        "helpful_count": 6,
        "reported_count": 0,
    },
    {
        "id": "blr_review_004",
        "person_id": "blr_vendor_002",
        "reviewer_id": "blr_user_5",
        "reviewer_username": "revathi_indiranagar",
        "rating": 4,
        "title": "Delayed finish but quality ok",
        "comment": "Had to nudge them thrice for final polish but the end result is solid. Will re-hire for study table.",
        "relationship": "repeat customer",
        "work_quality": 4,
        "communication": 3,
        "reliability": 3,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(20),
        "updated_at": _now(20),
        "is_verified": True,
        "helpful_count": 1,
        "reported_count": 0,
    },
    {
        "id": "blr_review_005",
        "person_id": "blr_vendor_003",
        "reviewer_id": "blr_user_1",
        "reviewer_username": "aditi_hsr",
        "rating": 5,
        "title": "Water leak fixed in 50 mins",
        "comment": "Logged a ticket on WhatsApp, plumber reached in under an hour and carried all parts.",
        "relationship": "tenant",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(2),
        "updated_at": _now(2),
        "is_verified": True,
        "helpful_count": 3,
        "reported_count": 0,
    },
    {
        "id": "blr_review_006",
        "person_id": "blr_vendor_003",
        "reviewer_id": "blr_user_4",
        "reviewer_username": "mohit_ulsoor",
        "rating": 4,
        "title": "Night support saved us",
        "comment": "They came at 11 PM to stop the main line leak. Slight premium but worth it.",
        "relationship": "facility manager",
        "work_quality": 4,
        "communication": 4,
        "reliability": 5,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(6),
        "updated_at": _now(6),
        "is_verified": True,
        "helpful_count": 4,
        "reported_count": 0,
    },
    {
        "id": "blr_review_007",
        "person_id": "blr_vendor_004",
        "reviewer_id": "blr_user_2",
        "reviewer_username": "rahul_koramangala",
        "rating": 5,
        "title": "Office fit-out experts",
        "comment": "Handled panel wiring for our co-working floor. They shared compliance photos daily.",
        "relationship": "startup founder",
        "work_quality": 5,
        "communication": 5,
        "reliability": 4,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(14),
        "updated_at": _now(14),
        "is_verified": True,
        "helpful_count": 2,
        "reported_count": 0,
    },
    {
        "id": "blr_review_008",
        "person_id": "blr_vendor_004",
        "reviewer_id": "blr_user_5",
        "reviewer_username": "revathi_indiranagar",
        "rating": 4,
        "title": "Great audit notes",
        "comment": "They shared a ten-point report for our apartment block and fixed half the issues same day.",
        "relationship": "association treasurer",
        "work_quality": 4,
        "communication": 4,
        "reliability": 4,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(18),
        "updated_at": _now(18),
        "is_verified": True,
        "helpful_count": 1,
        "reported_count": 0,
    },
    {
        "id": "blr_review_009",
        "person_id": "blr_vendor_005",
        "reviewer_id": "blr_user_3",
        "reviewer_username": "sahana_whitefield",
        "rating": 4,
        "title": "Fresh spinach everyday",
        "comment": "Greens are super fresh. Would love more millet options though.",
        "relationship": "subscriber",
        "work_quality": 4,
        "communication": 4,
        "reliability": 5,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(4),
        "updated_at": _now(4),
        "is_verified": True,
        "helpful_count": 0,
        "reported_count": 0,
    },
    {
        "id": "blr_review_010",
        "person_id": "blr_vendor_005",
        "reviewer_id": "blr_user_1",
        "reviewer_username": "aditi_hsr",
        "rating": 5,
        "title": "WhatsApp ops are smooth",
        "comment": "Pause/resume subscription is literally one emoji. Delivery bhaiya remembers to ring twice.",
        "relationship": "subscriber",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(1),
        "updated_at": _now(1),
        "is_verified": True,
        "helpful_count": 2,
        "reported_count": 0,
    },
    {
        "id": "blr_review_011",
        "person_id": "blr_vendor_006",
        "reviewer_id": "blr_user_4",
        "reviewer_username": "mohit_ulsoor",
        "rating": 5,
        "title": "Sofa restored in 24 hrs",
        "comment": "They picked up the recliner in the morning and returned it like new next day. Transparent costing.",
        "relationship": "customer",
        "work_quality": 5,
        "communication": 4,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(9),
        "updated_at": _now(9),
        "is_verified": True,
        "helpful_count": 3,
        "reported_count": 0,
    },
    {
        "id": "blr_review_012",
        "person_id": "blr_vendor_006",
        "reviewer_id": "blr_user_2",
        "reviewer_username": "rahul_koramangala",
        "rating": 4,
        "title": "Leather shade mismatch fixed",
        "comment": "Initial color was slightly off but they reworked quickly. Appreciate the honesty.",
        "relationship": "customer",
        "work_quality": 4,
        "communication": 4,
        "reliability": 4,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(11),
        "updated_at": _now(11),
        "is_verified": True,
        "helpful_count": 1,
        "reported_count": 0,
    },
    {
        "id": "blr_review_013",
        "person_id": "blr_vendor_007",
        "reviewer_id": "blr_user_5",
        "reviewer_username": "revathi_indiranagar",
        "rating": 5,
        "title": "Cycle camp for our RWA",
        "comment": "They serviced 25 kids cycles in our complex and taught basics. Parents loved it!",
        "relationship": "RWA coordinator",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(13),
        "updated_at": _now(13),
        "is_verified": True,
        "helpful_count": 5,
        "reported_count": 0,
    },
    {
        "id": "blr_review_014",
        "person_id": "blr_vendor_007",
        "reviewer_id": "blr_user_3",
        "reviewer_username": "sahana_whitefield",
        "rating": 4,
        "title": "Great for e-bikes",
        "comment": "Firmware update took a while but they loaned me a spare battery. Overall solid support.",
        "relationship": "regular customer",
        "work_quality": 4,
        "communication": 4,
        "reliability": 4,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(15),
        "updated_at": _now(15),
        "is_verified": True,
        "helpful_count": 1,
        "reported_count": 0,
    },
    {
        "id": "blr_review_015",
        "person_id": "blr_vendor_008",
        "reviewer_id": "blr_user_1",
        "reviewer_username": "aditi_hsr",
        "rating": 5,
        "title": "Best homely lunch",
        "comment": "Portions are generous and they tweak spice levels if you ask nicely.",
        "relationship": "subscriber",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(8),
        "updated_at": _now(8),
        "is_verified": True,
        "helpful_count": 2,
        "reported_count": 0,
    },
    {
        "id": "blr_review_016",
        "person_id": "blr_vendor_008",
        "reviewer_id": "blr_user_4",
        "reviewer_username": "mohit_ulsoor",
        "rating": 4,
        "title": "Delivery windows could tighten",
        "comment": "Food is great but sometimes arrives 20 mins late during rains.",
        "relationship": "subscriber",
        "work_quality": 4,
        "communication": 4,
        "reliability": 3,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(16),
        "updated_at": _now(16),
        "is_verified": True,
        "helpful_count": 0,
        "reported_count": 0,
    },
    {
        "id": "blr_review_017",
        "person_id": "blr_vendor_009",
        "reviewer_id": "blr_user_5",
        "reviewer_username": "revathi_indiranagar",
        "rating": 5,
        "title": "Veena repair pro",
        "comment": "Guruji sends all instruments here. They respect timelines for concerts.",
        "relationship": "student",
        "work_quality": 5,
        "communication": 4,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(12),
        "updated_at": _now(12),
        "is_verified": True,
        "helpful_count": 3,
        "reported_count": 0,
    },
    {
        "id": "blr_review_018",
        "person_id": "blr_vendor_009",
        "reviewer_id": "blr_user_2",
        "reviewer_username": "rahul_koramangala",
        "rating": 4,
        "title": "Guitar neck fixed",
        "comment": "Took five days but workmanship is better than most stores.",
        "relationship": "musician",
        "work_quality": 4,
        "communication": 4,
        "reliability": 4,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(19),
        "updated_at": _now(19),
        "is_verified": True,
        "helpful_count": 0,
        "reported_count": 0,
    },
    {
        "id": "blr_review_019",
        "person_id": "blr_vendor_010",
        "reviewer_id": "blr_user_3",
        "reviewer_username": "sahana_whitefield",
        "rating": 5,
        "title": "Pet van is spotless",
        "comment": "They call ahead, carry hypoallergenic shampoos and share photos during the service.",
        "relationship": "pet parent",
        "work_quality": 5,
        "communication": 5,
        "reliability": 5,
        "professionalism": 5,
        "would_recommend": True,
        "created_at": _now(5),
        "updated_at": _now(5),
        "is_verified": True,
        "helpful_count": 2,
        "reported_count": 0,
    },
    {
        "id": "blr_review_020",
        "person_id": "blr_vendor_010",
        "reviewer_id": "blr_user_1",
        "reviewer_username": "aditi_hsr",
        "rating": 4,
        "title": "Subscription is handy",
        "comment": "Wish weekend slots were easier to get but dogs love their spa van.",
        "relationship": "pet parent",
        "work_quality": 4,
        "communication": 4,
        "reliability": 4,
        "professionalism": 4,
        "would_recommend": True,
        "created_at": _now(9),
        "updated_at": _now(9),
        "is_verified": True,
        "helpful_count": 1,
        "reported_count": 0,
    },
]


def get_bangalore_seed_data() -> Dict[str, List[Dict]]:
    """Return users, persons, and reviews for Bengaluru-focused seeding."""
    return {
        "users": SEED_USERS,
        "persons": BANGALORE_VENDORS,
        "reviews": SEED_REVIEWS,
    }
